### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cellsite60** [starfish-app/Starfish#16]
Found a little typo in the description of Starfish in the Elementary OS AppCenter

![screenshot(1)](https://user-images.githubusercontent.com/83919459/144412995-e6e0655b-5980-4bb1-b9e6-429c840d6d76.png)

**Comment by Antolius** [comment]
Thank you for reporting this! Spelling is definitely my Achilles' heel, so I really appreciate it.
I'll fix this one right now and it should get picked up by AppCenter on the next release.
